language: node_js
node_js:
  - "4"

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: h4eDzXJF9zFAYi61IaJFPcJvL9cxtRlUq+BBvbYDKMJdq+dnqQWBMn7bIwvxcu75MzmzxQukTCN4Wm5hZRg66FypjQjVb3vsnsGkfbCztOJk0RL314MzJQX0UkcovAH4qkYLkvsrXODtDBS9BDupKL5AKKUl8n7DZLku4UuZDaXcsELrUFbAT3rWjW4MNACKPcPouKe3feU8sYCi0kqjX/eQ6H+bVFg+70bwZJLi8ZyMouEnxNaev4QG/RLUnmpMlshBxtWOCquXOLPmlWTBTMaqBlfyiGUDojkN+eAKykmVAS16/5UE07ILWwsJa2HxhD19LKRTW9lyb+xiL63TDq4kWJmAC6St+DNMyXvoTjDfOg0HOJMxJsus9A2xaoPaa9cT2FRlUw9gMDuM38WaV6i6WinZIFnFdd0mstJNR7otHc6P4vPNoRPZFAlmCadSSBtWpsP5+s7iGgbeCruklhZ+4XMRLfPlw6gmVO8lhdoqz60IX4iz8tufdPQPN0KJJS2vNlZzGF2dS/0ls/a0MtYzBECLxCH053LlzX1fcFIdS+paufGn3VP7ekK0VmxpE1peoRGd7EUDvP9PG9EWEGooCadaeVimckuygDyfKUOwTaxoXC4IcimqtXycXCd1AjeDVheZ7SLJtlPdVDKfHrTvMMIAeuxAsIQC6Heag8Y=

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  apt: true
  directories:
    - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh

before_script:
- ./.build_scripts/lint.sh
- npm test

script:
- NODE_ENV=production npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: .build_scripts/deploy.sh
  on:
    branch: ${DEPLOY_BRANCH}
